import type { Category, MenuItem } from '@/types/database'

export const FALLBACK_CATEGORIES: Category[] = [
  { id: 'starters', name: 'Starters', created_at: new Date().toISOString() },
  { id: 'mains', name: 'Main Course', created_at: new Date().toISOString() },
  { id: 'desserts', name: 'Desserts', created_at: new Date().toISOString() },
  { id: 'drinks', name: 'Drinks', created_at: new Date().toISOString() },
]

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const FALLBACK_MENU_ITEMS: MenuItem[] = ([
  // Starters
  {
    id: '1',
    category_id: 'starters',
    name: 'Seared Scallops',
    description: 'Pan-seared diver scallops with cauliflower purée, crispy capers, and brown butter emulsion.',
    price: 24,
    price_quarter: null, price_half: null, price_full: null,
    image_url: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=400&q=80&auto=format&fit=crop',
    is_bestseller: true,
    is_available: true,
    is_veg: false,
    is_spicy: false,
    is_chef_special: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    category_id: 'starters',
    name: 'Burrata & Heirloom Tomato',
    description: 'Creamy burrata with heirloom tomatoes, aged balsamic, fresh basil oil, and sea salt.',
    price: 18,
    image_url: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=400&q=80&auto=format&fit=crop',
    is_bestseller: false,
    is_available: true,
    is_veg: true,
    is_spicy: false,
    is_chef_special: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    category_id: 'starters',
    name: 'Wagyu Beef Tartare',
    description: 'Hand-cut A5 wagyu with egg yolk, cornichons, Dijon, and toasted sourdough crisps.',
    price: 32,
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&q=80&auto=format&fit=crop',
    is_bestseller: true,
    is_available: true,
    is_veg: false,
    is_spicy: false,
    is_chef_special: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    category_id: 'starters',
    name: 'Roasted Beet Salad',
    description: 'Candy-striped beets with whipped goat cheese, candied walnuts, and citrus vinaigrette.',
    price: 16,
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80&auto=format&fit=crop',
    is_bestseller: false,
    is_available: true,
    is_veg: true,
    is_spicy: false,
    is_chef_special: false,
    created_at: new Date().toISOString(),
  },
  // Mains
  {
    id: '5',
    category_id: 'mains',
    name: 'Dry-Aged Ribeye',
    description: '45-day dry-aged 16oz ribeye with bone marrow butter, roasted garlic, and truffle fries.',
    price: 78,
    image_url: 'https://images.unsplash.com/photo-1558030006-450675393462?w=400&q=80&auto=format&fit=crop',
    is_bestseller: true,
    is_available: true,
    is_veg: false,
    is_spicy: false,
    is_chef_special: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    category_id: 'mains',
    name: 'Pan-Roasted Duck Breast',
    description: 'Magret duck breast with cherry gastrique, parsnip purée, and wilted watercress.',
    price: 52,
    image_url: 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=400&q=80&auto=format&fit=crop',
    is_bestseller: true,
    is_available: true,
    is_veg: false,
    is_spicy: false,
    is_chef_special: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    category_id: 'mains',
    name: 'Wild Mushroom Risotto',
    description: 'Arborio rice with porcini, chanterelle, and truffle oil, finished with aged Parmigiano.',
    price: 38,
    image_url: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400&q=80&auto=format&fit=crop',
    is_bestseller: false,
    is_available: true,
    is_veg: true,
    is_spicy: false,
    is_chef_special: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    category_id: 'mains',
    name: 'Butter-Poached Lobster',
    description: 'Maine lobster tail poached in clarified butter with saffron beurre blanc and asparagus.',
    price: 68,
    image_url: 'https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=400&q=80&auto=format&fit=crop',
    is_bestseller: true,
    is_available: true,
    is_veg: false,
    is_spicy: false,
    is_chef_special: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '9',
    category_id: 'mains',
    name: 'Spiced Lamb Rack',
    description: 'Harissa-crusted lamb rack with pomegranate jus, roasted eggplant, and mint yogurt.',
    price: 58,
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&q=80&auto=format&fit=crop',
    is_bestseller: false,
    is_available: true,
    is_veg: false,
    is_spicy: true,
    is_chef_special: false,
    created_at: new Date().toISOString(),
  },
  // Desserts
  {
    id: '10',
    category_id: 'desserts',
    name: 'Valrhona Chocolate Fondant',
    description: 'Warm dark chocolate fondant with salted caramel ice cream and hazelnut praline.',
    price: 16,
    image_url: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=400&q=80&auto=format&fit=crop',
    is_bestseller: true,
    is_available: true,
    is_veg: true,
    is_spicy: false,
    is_chef_special: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '11',
    category_id: 'desserts',
    name: 'Crème Brûlée',
    description: 'Classic vanilla bean custard with a perfectly caramelised sugar crust and fresh berries.',
    price: 14,
    image_url: 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=400&q=80&auto=format&fit=crop',
    is_bestseller: false,
    is_available: true,
    is_veg: true,
    is_spicy: false,
    is_chef_special: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '12',
    category_id: 'desserts',
    name: 'Seasonal Tart',
    description: 'Buttery pâte sablée with pastry cream and the finest seasonal fruits from our farm partners.',
    price: 15,
    image_url: 'https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81?w=400&q=80&auto=format&fit=crop',
    is_bestseller: false,
    is_available: true,
    is_veg: true,
    is_spicy: false,
    is_chef_special: true,
    created_at: new Date().toISOString(),
  },
  // Drinks
  {
    id: '13',
    category_id: 'drinks',
    name: 'Ember Old Fashioned',
    description: 'Smoked bourbon, demerara syrup, Angostura bitters, and a charred orange peel.',
    price: 18,
    image_url: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=400&q=80&auto=format&fit=crop',
    is_bestseller: true,
    is_available: true,
    is_veg: true,
    is_spicy: false,
    is_chef_special: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '14',
    category_id: 'drinks',
    name: 'Garden Spritz',
    description: 'Elderflower liqueur, cucumber, fresh mint, prosecco, and a splash of lime.',
    price: 16,
    image_url: 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=400&q=80&auto=format&fit=crop',
    is_bestseller: false,
    is_available: true,
    is_veg: true,
    is_spicy: false,
    is_chef_special: false,
    created_at: new Date().toISOString(),
  },
  {
    id: '15',
    category_id: 'drinks',
    name: 'Reserve Burgundy',
    description: 'Domaine de la Romanée-Conti, Vosne-Romanée 2018. Silky, complex, and unforgettable.',
    price: 45,
    image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&q=80&auto=format&fit=crop',
    is_bestseller: false,
    is_available: true,
    is_veg: true,
    is_spicy: false,
    is_chef_special: true,
    created_at: new Date().toISOString(),
  },
] as any) as MenuItem[]

export const FALLBACK_BESTSELLERS: MenuItem[] = FALLBACK_MENU_ITEMS.filter(
  (item) => item.is_bestseller
).slice(0, 6)
